
DELETE FROM HANGMAN_MGMT_TABLE;

INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'DELIVER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'TECHNOLOGY');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'CUSTOMER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'CLOUD');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'COMPUTER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'SERVER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'ADVANCED');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'STORAGE');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'SOLUTIONS');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'COMMITMENT');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('DOMVS', 'MILESTONE');

